name: Publish and release extension

on:
  push:
    tags:
      - v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install extension dependencies
      run: npm ci

    - name: Tag does not contain a preview label; package normally
      if: ${{ !endsWith(github.ref, '-preview') }}
      run: npx vsce package

    - name: Tag contains preview label; package a preview version
      if: ${{ endsWith(github.ref, '-preview') }}
      run: npx vsce package --pre-release

    - name: Publish on Visual Studio Marketplace
      run: npx vsce publish -i *.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Publish on Eclipse Open VSX
      run: npx ovsx publish *.vsix
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}

    - name: Create release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: '*.vsix'
        prerelease: ${{ endsWith(github.ref, '-preview') }}
