name: Publish and release extension

on:
  push:
    tags:
      - v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Install package dependencies
      run: npm install

    - name: Tag does not contain a preview label; build and publish normally
      if: ${{ !endsWith(github.ref, '-preview') }}
      run: npm run deploy
      env:
        VSCE_PAT: ${{secrets.VSCE_PAT}}

    - name: Tag contains preview label; build and publish a preview version
      if: ${{ endsWith(github.ref, '-preview') }}
      run: npm run deployPreview
      env:
        VSCE_PAT: ${{secrets.VSCE_PAT}}

    - name: Package the extension so we can release to GitHub
      run: npx vsce package

    - name: Create release on GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: '*.vsix'
        body: See [CHANGELOG.md](https://github.com/deimonn/oro-theme/blob/master/CHANGELOG.md) for a list of additions, changes and fixes.
        prerelease: ${{ endsWith(github.ref, '-preview') }}
      env:
        GITHUB_TOKEN: ${{github.token}}
